//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace legaliteNET.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class legaliteEntities : DbContext
    {
        public legaliteEntities()
            : base("name=legaliteEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<actividade> actividades { get; set; }
        public virtual DbSet<asesore> asesores { get; set; }
        public virtual DbSet<solicitude> solicitudes { get; set; }
        public virtual DbSet<cliente> clientes { get; set; }
    
        public virtual ObjectResult<ActividadesEnElMes_Result> ActividadesEnElMes()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ActividadesEnElMes_Result>("ActividadesEnElMes");
        }
    
        public virtual ObjectResult<Trabajos_del_mes_asesor_Result> Trabajos_del_mes_asesor(Nullable<int> idasesor)
        {
            var idasesorParameter = idasesor.HasValue ?
                new ObjectParameter("idasesor", idasesor) :
                new ObjectParameter("idasesor", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Trabajos_del_mes_asesor_Result>("Trabajos_del_mes_asesor", idasesorParameter);
        }
    
        public virtual ObjectResult<Trabajos_del_mes_asesor_Result1> Trabajos_del_mes_asesores(Nullable<int> idasesor)
        {
            var idasesorParameter = idasesor.HasValue ?
                new ObjectParameter("idasesor", idasesor) :
                new ObjectParameter("idasesor", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Trabajos_del_mes_asesor_Result1>("Trabajos_del_mes_asesores", idasesorParameter);
        }
    }
}
